Repository p2p-org/key-app-android, pull requests merged in 2022-07, with the labels that each got.

#554 PWN-3868 - Add workflow to build apk
  .circleci/config.yml
  .github/actions/setup-apikey/action.yml
  .github/actions/setup-firebase/action.yml
  .github/actions/setup-gradle/action.yml
  .github/actions/setup-slack/action.yml
  .github/actions/setup-version/action.yml
  .github/workflows/android_build_feature.yml
  .github/workflows/android_lint.yml
  .github/workflows/android_unit_test.yml
Labels: WIP

#563 PWN-3776 - add Sentry integration
  .circleci/config.yml
  .gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/p2p/wallet/App.kt
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/CrashLogger.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/CrashLoggingFacade.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/CrashHttpLoggingInterceptor.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/FragmentLoggingLifecycleListener.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/TimberCrashTree.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/impl/FirebaseCrashlyticsFacade.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/impl/SentryFacade.kt
  app/src/main/java/org/p2p/wallet/common/crashlytics/CrashLoggingService.kt
  app/src/main/java/org/p2p/wallet/common/crashlytics/impl/GoogleFirebaseCrashlytics.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
  app/src/main/java/org/p2p/wallet/root/RootActivity.kt
Labels: Approved by QA

#575 [NO-TICKET] - Release AAB upload fix
  .circleci/config.yml
Labels: URGENT TO MERGE

#599 NO-TICKET - Add release workflow
  .github/workflows/android-release-workflow.yml
Labels: URGENT TO MERGE

#600 PWN-4283 - Fix addition of the RPC_POOL api key
  app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkEnvironmentManager.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcInterceptor.kt
Labels: URGENT TO MERGE
