Repository p2p-org/key-app-android, pull requests merged in 2022-03, with the labels that each got.

#299 [P2PW-1270] - Added fee corrections, added cache for frequent requests
  app/src/main/java/org/p2p/wallet/common/ui/dialogs/InfoDialog.kt
  app/src/main/java/org/p2p/wallet/feerelayer/FeeRelayerModule.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerAccountInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerSwapInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerTopUpInteractor.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/home/model/Token.kt
  app/src/main/java/org/p2p/wallet/renbtc/interactor/BurnBtcInteractor.kt
  app/src/main/java/org/p2p/wallet/rpc/RpcModule.kt
  app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionAddressInteractor.kt
  app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionAmountInteractor.kt
  app/src/main/java/org/p2p/wallet/rpc/repository/RpcAmountRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/rpc/repository/RpcAmountRepository.kt
  app/src/main/java/org/p2p/wallet/rpc/repository/RpcRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/rpc/repository/RpcRepository.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
  app/src/main/java/org/p2p/wallet/send/model/SendFee.kt
  app/src/main/java/org/p2p/wallet/send/model/SendTotal.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendContract.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendDetailsView.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/SwapInstructionsInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/serum/SerumOpenOrdersInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/serum/SerumSwapAmountInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/model/orca/SwapFee.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
  app/src/main/java/org/p2p/wallet/user/UserModule.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserAccountRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserAccountRepository.kt
  app/src/main/java/org/p2p/wallet/utils/DialogExtensions.kt
  app/src/main/res/layout/widget_send_details.xml
  app/src/main/res/layout/widget_swap_details.xml
  app/src/main/res/values/strings.xml
  solanaj/src/main/java/org/p2p/solanaj/kits/TokenTransaction.kt
Labels: PR TOO BIG

#349 [P2PW-1482] Search token error
  app/src/main/java/org/p2p/wallet/receive/list/TokenListContract.kt
  app/src/main/java/org/p2p/wallet/receive/list/TokenListData.kt
  app/src/main/java/org/p2p/wallet/receive/list/TokenListFragment.kt
  app/src/main/java/org/p2p/wallet/receive/list/TokenListPresenter.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserLocalRepository.kt
  app/src/main/res/layout/fragment_receive_list.xml
  app/src/main/res/values/strings.xml
Labels: Wrong branch name

#356 P2PW-1482 - Fix search tokens method
  app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
  app/src/main/res/drawable/bg_system_error_main_rounded_solid.xml
  app/src/main/res/layout/fragment_receive_list.xml
Labels: Approved by QA

#354 P2PW-1432 - make secretWords autoResizable
  app/src/main/res/layout/item_secret_key.xml
  app/src/main/res/layout/item_security_key.xml
Labels: Approved by QA

#344 [P2PW-1479] pass original token symbol to show on UI not only solana
  app/src/main/java/org/p2p/wallet/send/model/SendFee.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
Labels: Wrong PR name

#352 P2PW-1533 - fix usdc token to pass in moon pay in needed format
  app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaPresenter.kt
Labels: Wrong branch name, Approved by QA

#355 P2PW-1534 - Refactor setStatusBarColor and setStatusBarIconColors, re…
  app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
  app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcFragment.kt
  app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/reset/seedinfo/SeedInfoFragment.kt
Labels: Approved by QA

#360 P2PW-1230 - QRCode is now sharing image + address
  app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/repository/FileRepository.kt
  app/src/main/java/org/p2p/wallet/auth/ui/security/SecurityKeyContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/security/SecurityKeyFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/security/SecurityKeyPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/username/UsernameContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/username/UsernameFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/username/UsernamePresenter.kt
  app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcContract.kt
  app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcFragment.kt
  app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcPresenter.kt
  app/src/main/java/org/p2p/wallet/receive/solana/ReceiveSolanaContract.kt
  app/src/main/java/org/p2p/wallet/receive/solana/ReceiveSolanaFragment.kt
  app/src/main/java/org/p2p/wallet/receive/solana/ReceiveSolanaPresenter.kt
  app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenContract.kt
  app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenFragment.kt
  app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenPresenter.kt
  app/src/main/java/org/p2p/wallet/receive/widget/QrView.kt
  app/src/main/java/org/p2p/wallet/receive/widget/ReceiveCardView.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCContract.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCFragment.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCPresenter.kt
  app/src/main/java/org/p2p/wallet/settings/ui/reset/seedinfo/SeedInfoFragment.kt
  app/src/main/java/org/p2p/wallet/utils/ContextExtensions.kt
  app/src/main/res/layout/widget_qr_view.xml
Labels: Approved by QA

#340 P2PW-1478 - Recipient screen fixes
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerAccountInteractor.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/data/ServerError.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/ServerErrorInterceptor.kt
  app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionAddressInteractor.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
  app/src/main/java/org/p2p/wallet/send/ui/search/SearchContract.kt
  app/src/main/java/org/p2p/wallet/send/ui/search/SearchFragment.kt
  app/src/main/java/org/p2p/wallet/send/ui/search/SearchPresenter.kt
  app/src/main/res/layout/fragment_search.xml
  solanaj/src/main/java/org/p2p/solanaj/core/Message.java
  solanaj/src/main/java/org/p2p/solanaj/core/PublicKey.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/Pool.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/TokenTransaction.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/LockAndMint.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/SolanaChain.java
  solanaj/src/main/java/org/p2p/solanaj/programs/SystemProgram.kt
  solanaj/src/main/java/org/p2p/solanaj/programs/TokenProgram.java
  solanaj/src/main/java/org/p2p/solanaj/serumswap/utils/SerumSwapUtils.kt
  solanaj/src/main/java/org/p2p/solanaj/utils/PublicKeyValidator.kt
Labels: Approved by QA

#351 P2PW-1260 - Change scale type of buy amount and change button text
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/receive/network/ReceiveNetworkTypePresenter.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/info/RenBtcBuyBottomSheet.kt
  app/src/main/java/org/p2p/wallet/rpc/RpcModule.kt
  app/src/main/java/org/p2p/wallet/rpc/interactor/CloseInteractor.kt
  app/src/main/java/org/p2p/wallet/rpc/interactor/TokenInteractor.kt
  app/src/main/res/layout/dialog_btc_buy_info.xml
  app/src/main/res/values/strings.xml
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/RenVMProvider.java
Labels: Approved by QA

#357 P2PW-1412 - fix amounts on Send Screen
  app/src/main/java/org/p2p/wallet/home/model/Token.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenHiddenViewHolder.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenViewHolder.kt
  app/src/main/java/org/p2p/wallet/send/model/SendTotal.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/java/org/p2p/wallet/utils/AmountExtensions.kt
Labels: Approved by QA

#366 P2PW-1582 transaction limits dialog added on OrcaSwapFragment.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FreeTransactionFeeLimit.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapContract.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/SwapDetailsView.kt
Labels: Approved by QA

#365 P2PW-1573 - migrate WebSocket to kotlin
  app/src/main/java/org/p2p/wallet/updates/SocketUpdatesManager.kt
  app/src/main/java/org/p2p/wallet/utils/NoOp.kt
  solanaj/src/main/java/org/p2p/solanaj/ws/NotificationEventListener.java
  solanaj/src/main/java/org/p2p/solanaj/ws/NotificationEventListener.kt
  solanaj/src/main/java/org/p2p/solanaj/ws/SignatureNotification.java
  solanaj/src/main/java/org/p2p/solanaj/ws/SignatureNotification.kt
  solanaj/src/main/java/org/p2p/solanaj/ws/SocketStateListener.kt
  solanaj/src/main/java/org/p2p/solanaj/ws/SubscriptionWebSocketClient.java
  solanaj/src/main/java/org/p2p/solanaj/ws/SubscriptionWebSocketClient.kt
Labels: Approved by QA

#370 P2PW-1598 - fix token amount formatter by adding maximumFractionDigits
  app/src/main/java/org/p2p/wallet/utils/AmountUtils.kt
Labels: Approved by QA

#368 P2PW-1263 - Token swipes fixes
  app/src/main/java/org/p2p/wallet/common/ui/recycler/SwipeLayout.java
  app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenHiddenViewHolder.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenViewHolder.kt
  app/src/main/res/drawable/ic_hide.xml
  app/src/main/res/drawable/ic_show.xml
  app/src/main/res/layout/item_token.xml
  app/src/main/res/layout/item_token_hidden.xml
  app/src/main/res/values/attrs.xml
  solanaj/src/main/res/drawable/ic_hide.xml
Labels: Approved by QA

#371 P2PW-1635 - ProgressBottomSheet buttons redesign
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
  app/src/main/java/org/p2p/wallet/transaction/ui/ProgressBottomSheet.kt
  app/src/main/res/layout/dialog_transaction_progress.xml
  app/src/main/res/values/strings.xml
Labels: Approved by QA

#379 PWN-1552 - Fix hidden tokens arrow image rotation
  app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
Labels: Approved by QA

#378 PWN-3074 - Fix crash in reset seed phrase screen
  app/src/main/java/org/p2p/wallet/settings/ui/reset/seedphrase/ResetSeedPhraseFragment.kt
Labels: Approved by QA

#361 P2PW-1491 - fix NPE RootActivity crash + Crashlytics integration
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/feature/res/mipmap-hdpi/ic_launcher.png
  app/src/feature/res/mipmap-hdpi/ic_launcher_round.png
  app/src/feature/res/mipmap-mdpi/ic_launcher.png
  app/src/feature/res/mipmap-mdpi/ic_launcher_round.png
  app/src/feature/res/mipmap-xhdpi/ic_launcher.png
  app/src/feature/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/feature/res/mipmap-xxhdpi/ic_launcher.png
  app/src/feature/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/feature/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/feature/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/feature/res/values/strings.xml
  app/src/main/java/org/p2p/wallet/App.kt
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
  app/src/main/java/org/p2p/wallet/common/crashlytics/CrashHttpLoggingInterceptor.kt
  app/src/main/java/org/p2p/wallet/common/crashlytics/CrashLoggingService.kt
  app/src/main/java/org/p2p/wallet/common/crashlytics/FragmentLoggingLifecycleListener.kt
  app/src/main/java/org/p2p/wallet/common/crashlytics/TimberCrashTree.kt
  app/src/main/java/org/p2p/wallet/common/crashlytics/impl/GoogleFirebaseCrashlytics.kt
  app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
  app/src/main/java/org/p2p/wallet/common/mvp/BasePresenter.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/DebugHttpLoggingLogger.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt
  app/src/main/java/org/p2p/wallet/renbtc/RenBtcModule.kt
  app/src/main/java/org/p2p/wallet/root/RootActivity.kt
  app/src/main/java/org/p2p/wallet/user/UserModule.kt
  app/src/main/java/org/p2p/wallet/utils/StdExtensions.kt
  scripts/changelog.gradle
Labels: Approved by QA

#385 PWN-3049 - Disable skip for ReserveUsernameFragment opened from Home
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
Labels: Approved by QA

#377 P2PW-1589 - Adaptive amount text size in send and swap
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
  app/src/main/res/layout/fragment_send.xml
  app/src/main/res/layout/fragment_swap_orca.xml
  app/src/main/res/layout/fragment_swap_serum.xml
Labels: Approved by QA

#389 PWN-3109 PWN-3110 - TransactionHistory list bugfixes
  app/proguard-rules.pro
  app/src/main/java/org/p2p/wallet/common/ui/recycler/EndlessScrollListener.kt
  app/src/main/java/org/p2p/wallet/common/ui/recycler/PagingState.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/DateViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/EmptyViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/ErrorViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/HistoryAdapter.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/HistoryAdapterPagingController.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/ProgressViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/TransactionViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/holders/DateViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/holders/EmptyViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/holders/ErrorViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/holders/HistoryTransactionViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/holders/ProgressViewHolder.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/adapter/holders/TransactionViewHolder.kt
  app/src/main/java/org/p2p/wallet/utils/viewbinding/ViewBindingDelegateExtensions.kt
  app/src/main/java/org/p2p/wallet/utils/viewbinding/ViewBindingExtensions.kt
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/values/dimens.xml
Labels: Approved by QA

#396 PWN-3065 - update main screen after environment is changed
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/home/model/VisibilityState.kt
  app/src/main/java/org/p2p/wallet/home/repository/HomeDatabaseRepository.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeElementItemMapper.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/environment/EnvironmentManager.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcInterceptor.kt
  app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
Labels: Approved by QA

#394 PWN-3079 - hide devNet on builds for prod
  app/build.gradle
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/common/AppFeatureFlags.kt
  app/src/main/java/org/p2p/wallet/debugdrawer/ConfigurationModule.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
  app/src/main/java/org/p2p/wallet/settings/SettingsModule.kt
  app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkContract.kt
  app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkPresenter.kt
  app/src/main/res/layout/fragment_settings_network.xml
  app/src/main/res/layout/view_debug_drawer_configure_environment.xml
Labels: Approved by QA

#390 PWN-3081 - Fixed disabled broken state on HomeScreen
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/home/MainFragment.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt
  app/src/main/java/org/p2p/wallet/intercom/IntercomService.kt
  app/src/main/java/org/p2p/wallet/utils/viewbinding/FragmentViewBindingPropertyDelegate.kt
  app/src/main/java/org/p2p/wallet/utils/viewbinding/ViewBindingDelegateExtensions.kt
Labels: Approved by QA

#347 P2PW-1484 - do not show info warning block on transfering SOL tokens
  app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendContract.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
  app/src/main/res/values/strings.xml
Labels: Approved by QA
