Repository p2p-org/key-app-android, pull requests merged in 2022-10, with the labels that each got.

#820 PWN-5330 - Add restore state pattern
  app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/UserSignUpInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/TorusKeyInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/model/ErrorScreenButtons.kt
  app/src/main/java/org/p2p/wallet/auth/model/OnboardingFlow.kt
  app/src/main/java/org/p2p/wallet/auth/model/RestoreUserResult.kt
  app/src/main/java/org/p2p/wallet/auth/repository/RestoreUserExceptionHandler.kt
  app/src/main/java/org/p2p/wallet/auth/statemachine/RestoreState.kt
  app/src/main/java/org/p2p/wallet/auth/statemachine/RestoreStateMachine.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestorePresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenPresenter.kt
  app/src/main/res/drawable-v24/onboarding_box.png
  app/src/main/res/drawable/image_box.png
  app/src/main/res/layout/fragment_new_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_general_error.xml
  app/src/main/res/layout/fragment_onboarding_slide.xml
  app/src/main/res/layout/fragment_restore_error_screen.xml
Labels: URGENT TO MERGE

#823 PWN-5330 - Fix last restore edge cases
  app/src/main/java/org/p2p/wallet/auth/interactor/RestoreStateMachine.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/model/RestoreHandledState.kt
  app/src/main/java/org/p2p/wallet/auth/repository/RestoreUserResultHandler.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestorePresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
  app/src/main/res/layout/fragment_onboarding_general_error.xml
  app/src/main/res/values/onboarding_strings.xml
  app/src/main/res/values/strings.xml
Labels: URGENT TO MERGE

#824 PWN-5330 - Fix restore errors
  app/build.gradle
  app/src/main/java/org/p2p/wallet/auth/interactor/CreateWalletInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/UserSignUpInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/CustomShareRestoreInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/repository/GatewayServiceErrorHandler.kt
  app/src/main/java/org/p2p/wallet/auth/repository/RestoreUserResultHandler.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
  app/src/main/res/layout/fragment_onboarding_general_error.xml
  app/src/main/res/layout/fragment_restore_error_screen.xml
  app/src/main/res/values/onboarding_strings.xml
Labels: URGENT TO MERGE

#828 PWN-5330 fix onboarding text and some bugs
  app/build.gradle
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/repository/RestoreUserResultHandler.kt
  app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/continuestep/ContinueOnboardingPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundPresenter.kt
  app/src/main/res/layout/fragment_new_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_general_error.xml
  app/src/main/res/layout/fragment_onboarding_general_error_timer.xml
  app/src/main/res/values/onboarding_strings.xml
Labels: URGENT TO MERGE

#848 PWN-3713 - latest release changes
  app/src/main/assets/index.html
  app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
  app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkServicesUrlProvider.kt
  app/src/main/res/values/environment_config.xml
  app/src/main/res/xml/network_security_config.xml
Labels: WIP

#850 Release v1.13.0 - cherry picked lost tasks
  app/gradle.properties
  app/src/main/java/org/p2p/wallet/common/analytics/constants/EventNames.kt
  app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
  app/src/main/java/org/p2p/wallet/moonpay/BuyModule.kt
  app/src/main/java/org/p2p/wallet/moonpay/analytics/BuyAnalytics.kt
  app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaPresenter.kt
  app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyContract.kt
  app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt
Labels: URGENT TO MERGE

#859 NO-TICKET - Сonsequences after MERGE with RESTORE
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
  app/src/main/java/org/p2p/wallet/home/MainFragment.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/bottomsheet/ActionsBottomSheet.kt
  app/src/main/java/org/p2p/wallet/sdk/facade/SolendSdkFacade.kt
  app/src/main/java/org/p2p/wallet/utils/NetworkExtensions.kt
  app/src/main/res/xml/backup_rules.xml
Labels: URGENT TO MERGE

#882 PWN-5599 - solend invest stub fragment
  app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnContract.kt
  app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnFragment.kt
  app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnPresenter.kt
  app/src/main/java/org/p2p/wallet/solend/ui/earn/StubSolendEarnFragment.kt
  app/src/main/res/drawable/ic_solend_stub_earn.xml
  app/src/main/res/layout/fragment_solend_stub_earn.xml
  app/src/main/res/values/solend_strings.xml
Labels: Do not merge

#879 PWN-5587 - NameService. Feature toggles and into app screen integration
  app/src/main/assets/index.html
  app/src/main/java/org/p2p/wallet/appsfly/AppsFlyerService.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/OnboardingReserveUsernameFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/OnboardingReserveUsernamePresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/widget/ReserveUsernameInputView.kt
  app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyPresenter.kt
  app/src/main/java/org/p2p/wallet/auth/username/api/response/GetNameResponse.kt
  app/src/main/java/org/p2p/wallet/auth/username/api/response/ResolveNameResponse.kt
  app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt
  app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/RegisterUsernameEnabledFeatureToggle.kt
  app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/RegisterUsernameSkipEnabledFeatureToggle.kt
  app/src/main/java/org/p2p/wallet/common/ui/widget/InputTextView.kt
  app/src/main/java/org/p2p/wallet/debug/torus/DebugTorusFragment.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkEnvironmentManager.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkServicesUrlProvider.kt
  app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
  app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhrasePresenter.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
  app/src/main/java/org/p2p/wallet/send/model/SearchTarget.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/java/org/p2p/wallet/send/ui/search/SearchContract.kt
  app/src/main/java/org/p2p/wallet/send/ui/search/SearchFragment.kt
  app/src/main/java/org/p2p/wallet/send/ui/search/SearchPresenter.kt
  app/src/main/java/org/p2p/wallet/settings/model/SettingsItemMapper.kt
  app/src/main/java/org/p2p/wallet/settings/ui/settings/NewSettingsPresenter.kt
  app/src/main/res/layout/fragment_onboarding_reserve_username.xml
  app/src/main/res/layout/fragment_reserve_username.xml
  app/src/main/res/layout/layout_home_toolbar.xml
  app/src/main/res/layout/widget_reserve_username_input_view.xml
  app/src/main/res/values/onboarding_strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  app/src/test/java/org/p2p/wallet/send/ui/main/SendPresenterTest.kt
Labels: Do not merge, PR TOO BIG, QA in progress

#900 PWN-5669 - Keystore crash
  app/src/main/java/org/p2p/wallet/AppPrefsBackupAgent.kt
  app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
  app/src/main/java/org/p2p/wallet/common/crypto/keystore/EncoderDecoderMarshmallow.kt
  app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
  app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorage.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt
  app/src/main/java/org/p2p/wallet/infrastructure/security/SecureStorage.kt
Labels: HOTFIX
