Repository p2p-org/key-app-android, pull requests merged in 2022-06, with the labels that each got.

#508 PWN-3560 - Сoin gecko as the second source of token prices
  app/src/main/java/org/p2p/wallet/App.kt
  app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
  app/src/main/java/org/p2p/wallet/auth/repository/FileRepository.kt
  app/src/main/java/org/p2p/wallet/common/AppFeatureFlags.kt
  app/src/main/java/org/p2p/wallet/common/BooleanPreference.kt
  app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesPresenter.kt
  app/src/main/java/org/p2p/wallet/debugdrawer/ConfigurationModule.kt
  app/src/main/java/org/p2p/wallet/home/api/CoinGeckoApi.kt
  app/src/main/java/org/p2p/wallet/home/api/CryptoCompareApi.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
  app/src/main/java/org/p2p/wallet/user/UserModule.kt
  app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/TokenPricesRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/TokenSymbol.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/di/TokenPricesModule.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCoinGeckoRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCryptoCompareRepository.kt
  app/src/main/res/values/environment_config.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/p2p/wallet/swap/koin/CheckModulesTest.kt
Labels: URGENT TO MERGE

#515 PWN-3753 - fix release/develop AAB upload RELEASE
  .circleci/config.yml
  app/build.gradle
Labels: Approved by QA

#519 PWN-3753 - Fix API keys filling for develop
  .circleci/config.yml
  app/build.gradle
Labels: Approved by QA

#524 PWN-3680 - add new color palette in UI Kit
  app/build.gradle
  app/src/main/java/org/p2p/wallet/history/ui/details/TransactionDetailsFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/TransactionDetailsBottomSheetFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/TransactionSwapViewHolder.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/transactions/RenTransactionsAdapter.kt
  app/src/main/res/drawable/bg_line_chart.xml
  app/src/main/res/layout/dialog_transaction_details.xml
  app/src/main/res/layout/fragment_transaction_transfer.xml
  app/src/main/res/layout/item_receive_status.xml
  app/src/main/res/layout/item_ren_transaction.xml
  app/src/main/res/layout/widget_swap_details.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/palette.xml
  ui-kit/src/main/res/values/white_palette.xml
Labels: Approved by QA

#510 PWN-3748 - Swap/Send screen selection mechanism / Part 2
  app/build.gradle
  app/src/main/java/org/p2p/wallet/common/mvp/BasePresenter.kt
  app/src/main/java/org/p2p/wallet/common/ui/textwatcher/AmountFractionTextWatcher.kt
  app/src/main/java/org/p2p/wallet/feerelayer/FeeRelayerModule.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInstructionsInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FeePayerSelectionStrategy.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerFee.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/home/model/Token.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
  app/src/main/java/org/p2p/wallet/send/model/SendButton.kt
  app/src/main/java/org/p2p/wallet/send/model/SendFee.kt
  app/src/main/java/org/p2p/wallet/send/model/SendPresenterState.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendContract.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
  app/src/main/java/org/p2p/wallet/swap/api/InternalWebApi.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaInfoInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/model/FeeRelayerSwapFee.kt
  app/src/main/java/org/p2p/wallet/swap/model/SwapButton.kt
  app/src/main/java/org/p2p/wallet/swap/model/SwapDetailsState.kt
  app/src/main/java/org/p2p/wallet/swap/model/orca/OrcaConverter.kt
  app/src/main/java/org/p2p/wallet/swap/model/orca/SwapFee.kt
  app/src/main/java/org/p2p/wallet/swap/model/orca/SwapState.kt
  app/src/main/java/org/p2p/wallet/swap/model/orca/SwapTotal.kt
  app/src/main/java/org/p2p/wallet/swap/repository/OrcaSwapRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapContract.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/SwapDetailsView.kt
  app/src/main/java/org/p2p/wallet/transaction/di/TransactionModule.kt
  app/src/main/java/org/p2p/wallet/transaction/interactor/TransactionBuilderInteractor.kt
  app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
  app/src/main/res/layout/fragment_send.xml
  app/src/main/res/layout/fragment_swap_orca.xml
  app/src/main/res/layout/item_settings_row_item.xml
  app/src/main/res/layout/widget_account_fee_view.xml
  app/src/main/res/layout/widget_swap_details.xml
  app/src/main/res/values/environment_config.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/p2p/wallet/send/ui/main/SendPresenterTest.kt
  app/src/test/java/org/p2p/wallet/utils/CoroutineExtension.kt
  app/src/test/java/org/p2p/wallet/utils/SpyOnInjectMockKsExtension.kt
Labels: URGENT TO MERGE, PR TOO BIG

#544 PWN-3681 - UiKit Bottom Navigation View
  app/build.gradle
  app/src/main/res/layout/fragment_main.xml
  scripts/common-library.gradle
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/LockAndMint.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/transaction/parser/OrcaSwapInstructionParser.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/transaction/parser/SerumSwapInstructionParser.kt
  ui-kit/build.gradle
  ui-kit/src/main/kotlin/org/p2p/uikit/organisms/UiKitBottomNavigationView.kt
  ui-kit/src/main/res/color/bottom_navigation_item_tint.xml
  ui-kit/src/main/res/drawable/ic_action_account_balance_wallet.xml
  ui-kit/src/main/res/drawable/ic_action_account_balance_wallet_filled.xml
  ui-kit/src/main/res/drawable/ic_action_history.xml
  ui-kit/src/main/res/drawable/ic_action_schedule.xml
  ui-kit/src/main/res/drawable/ic_action_settings.xml
  ui-kit/src/main/res/drawable/ic_action_settings_filled.xml
  ui-kit/src/main/res/drawable/ic_action_watch_later.xml
  ui-kit/src/main/res/drawable/ic_bottom_navigation_feedback.xml
  ui-kit/src/main/res/drawable/ic_bottom_navigation_history.xml
  ui-kit/src/main/res/drawable/ic_bottom_navigation_send.xml
  ui-kit/src/main/res/drawable/ic_bottom_navigation_settings.xml
  ui-kit/src/main/res/drawable/ic_bottom_navigation_wallet.xml
  ui-kit/src/main/res/drawable/ic_communication_email.xml
  ui-kit/src/main/res/drawable/ic_content_forward.xml
  ui-kit/src/main/res/drawable/ic_content_mail.xml
  ui-kit/src/main/res/drawable/ic_navigation_arrow_upward.xml
  ui-kit/src/main/res/drawable/shape_bottom_navigation_background.xml
  ui-kit/src/main/res/drawable/shape_bottom_navigation_selected.xml
  ui-kit/src/main/res/menu/menu_ui_kit_bottom_navigation.xml
  ui-kit/src/main/res/values/dimen.xml
  ui-kit/src/main/res/values/strings.xml
  ui-kit/src/main/res/values/styles.xml
  ui-kit/src/main/res/values/styles_buttons.xml
  ui-kit/src/main/res/values/typography.xml
Labels: Approved by QA

#553 NO-TICKET - develop fix after UiKitBottomNavigationView
  app/src/main/res/layout/fragment_main.xml
Labels: URGENT TO MERGE
