Repository p2p-org/key-app-android, pull requests merged in 2022-05, with the labels that each got.

#485 PWN-3575 - Added info object to all fee relayer transactions and fixed fees for top up
  app/src/main/java/org/p2p/wallet/feerelayer/api/FeeRelayerInfoRequest.kt
  app/src/main/java/org/p2p/wallet/feerelayer/api/RelayTopUpSwapRequest.kt
  app/src/main/java/org/p2p/wallet/feerelayer/api/SendTransactionRequest.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerTopUpInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerConverter.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerStatistics.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/RelayAccount.kt
  app/src/main/java/org/p2p/wallet/feerelayer/repository/FeeRelayerRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/feerelayer/repository/FeeRelayerRepository.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
  app/src/main/java/org/p2p/wallet/utils/Constants.kt
  solanaj/src/main/java/org/p2p/solanaj/core/OperationType.kt
Labels: URGENT TO MERGE

#490 PWN-3608 - Hotfix for fee relayer
  app/gradle.properties
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerAccountInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerSwapInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerTopUpInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/RelayAccount.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/RelayInfo.kt
Labels: URGENT TO MERGE, HOTFIX

#483 PWN-3436 - fix Wallet_Created event send
  app/src/main/java/org/p2p/wallet/auth/analytics/OnboardingAnalytics.kt
  app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyContract.kt
  app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyPresenter.kt
Labels: Approved by QA

#391 PWN-2819 - Remove rpc client from solana
  app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/environment/EnvironmentManager.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcInterceptor.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcSolanaInterceptor.kt
  app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcFragment.kt
  app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcPresenter.kt
  app/src/main/java/org/p2p/wallet/renbtc/RenBtcModule.kt
  app/src/main/java/org/p2p/wallet/renbtc/RenTransactionManager.kt
  app/src/main/java/org/p2p/wallet/renbtc/interactor/BurnBtcInteractor.kt
  app/src/main/java/org/p2p/wallet/renbtc/interactor/RenBtcInteractor.kt
  app/src/main/java/org/p2p/wallet/renbtc/repository/RenDatabaseRepository.kt
  app/src/main/java/org/p2p/wallet/renbtc/service/RenStatusExecutor.kt
  app/src/main/java/org/p2p/wallet/renbtc/service/RenVMService.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCContract.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCFragment.kt
  app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCPresenter.kt
  app/src/main/java/org/p2p/wallet/rpc/RpcModule.kt
  app/src/main/java/org/p2p/wallet/rpc/repository/solana/RpcSolanaApi.kt
  app/src/main/java/org/p2p/wallet/rpc/repository/solana/RpcSolanaRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/res/layout/fragment_receive_ren_btc.xml
  solanaj/build.gradle
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/BurnAndRelease.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/BurnDetails.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/GatewayRegistryData.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/LockAndMint.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/LockAndMint.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/NetworkConfig.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/SolanaChain.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/HashUtils.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/RenVMProvider.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/RenVMRepository.kt
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/types/ParamsSubmitMint.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/types/ResponseQueryBlockState.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/types/ResponseQueryConfig.java
  solanaj/src/main/java/org/p2p/solanaj/kits/renBridge/renVM/types/ResponseQueryTxMint.java
  solanaj/src/main/java/org/p2p/solanaj/model/types/ConfirmedTransaction.java
  solanaj/src/main/java/org/p2p/solanaj/model/types/ProgramSwapAccount.java
  solanaj/src/main/java/org/p2p/solanaj/model/types/QRAccountInfo.java
  solanaj/src/main/java/org/p2p/solanaj/model/types/RpcNotificationResult.java
  solanaj/src/main/java/org/p2p/solanaj/model/types/RpcQrAccountInfoConfig.java
  solanaj/src/main/java/org/p2p/solanaj/model/types/RpcResponse.java
  solanaj/src/main/java/org/p2p/solanaj/model/types/SignatureInformationResponse.kt
  solanaj/src/main/java/org/p2p/solanaj/programs/SystemProgram.kt
  solanaj/src/main/java/org/p2p/solanaj/rpc/RpcApi.java
  solanaj/src/main/java/org/p2p/solanaj/rpc/RpcClient.java
  solanaj/src/main/java/org/p2p/solanaj/rpc/RpcEnvironment.kt
  solanaj/src/main/java/org/p2p/solanaj/rpc/RpcSolanaInteractor.kt
  solanaj/src/main/java/org/p2p/solanaj/rpc/RpcSolanaRepository.kt
  solanaj/src/test/java/org/p2p/solanaj/kits/renBridge/BurnAndReleaseTest.java
  solanaj/src/test/java/org/p2p/solanaj/kits/renBridge/LockAndMintTest.java
  solanaj/src/test/java/org/p2p/solanaj/kits/renBridge/Mock.java
  solanaj/src/test/java/org/p2p/solanaj/kits/renBridge/SolanaChainTest.java
  solanaj/src/test/java/org/p2p/solanaj/kits/renBridge/renVM/RenVMProviderTest.java
Labels: PR TOO BIG
