Repository p2p-org/key-app-android, pull requests merged in 2022-04, with the labels that each got.

#407 PWN-3172 - Save and restore hidden tokens visibility state
  app/src/main/java/org/p2p/wallet/home/model/VisibilityState.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
  app/src/main/java/org/p2p/wallet/user/UserModule.kt
  app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
Labels: Approved by QA

#402 PWN-3144 - Back press fix in OnboardingFragment
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/OnboardingFragment.kt
Labels: Approved by QA

#412 PWN-3159 - Add _debug events in analytics for feature builds
  app/build.gradle
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/common/analytics/Analytics.kt
  app/src/main/java/org/p2p/wallet/common/analytics/TrackersFactory.kt
  app/src/main/java/org/p2p/wallet/common/analytics/trackers/AmplitudeTracker.kt
Labels: QA in progress

#400 PWN-3169 - Fix cached user error on send
  app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionAddressInteractor.kt
  app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
Labels: Approved by QA

#418 PWN-3253 - transaction details bottom sheet implementation
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/common/date/ZonedDateExtensions.kt
  app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt
  app/src/main/java/org/p2p/wallet/history/HistoryModule.kt
  app/src/main/java/org/p2p/wallet/history/model/HistoryTransaction.kt
  app/src/main/java/org/p2p/wallet/history/ui/details/TransactionDetailsPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/TransactionDetailsBottomSheetContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/TransactionDetailsBottomSheetFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/TransactionDetailsBottomSheetPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/TransactionViewHolder.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/restore/BackupModule.kt
  app/src/main/res/drawable/bg_app_stroke_rounded.xml
  app/src/main/res/layout/dialog_transaction_details.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles_fonts.xml
Labels: WIP

#386 PWN-3096 - make error handling from FeeRelayer
  app/proguard-rules.pro
  app/src/main/java/org/p2p/wallet/infrastructure/network/data/ErrorCode.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/data/ServerError.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/data/ServerException.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/ErrorType.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/ErrorTypeConverter.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerError.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerErrorData.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerErrorDetails.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerErrorMapper.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerErrorType.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerInterceptor.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcInterceptor.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
  app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
  app/src/main/java/org/p2p/wallet/transaction/model/TransactionState.kt
  app/src/main/res/layout/dialog_transaction_progress.xml
  app/src/main/res/values/strings.xml
Labels: Approved by QA

#430 PWN-3278 - calculateFees before calculateAmount as fees could be null in calculateAmount
  app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
Labels: Approved by QA

#427 PWN-3272 - Fix error when trying to buy USDC with Moonpay
  app/src/main/java/org/p2p/wallet/common/ui/widget/OptionsTextView.kt
  app/src/main/java/org/p2p/wallet/home/HomeModule.kt
  app/src/main/java/org/p2p/wallet/moonpay/api/MoonpayBuyCurrencyResponse.kt
  app/src/main/java/org/p2p/wallet/moonpay/api/MoonpayCurrencyResponse.kt
  app/src/main/java/org/p2p/wallet/moonpay/model/BuyCurrency.kt
  app/src/main/java/org/p2p/wallet/moonpay/model/BuyViewData.kt
  app/src/main/java/org/p2p/wallet/moonpay/repository/MoonpayApiMapper.kt
  app/src/main/java/org/p2p/wallet/moonpay/repository/MoonpayRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/moonpay/repository/MoonpayRepository.kt
  app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaContract.kt
  app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaFragment.kt
  app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaPresenter.kt
Labels: Approved by QA

#436 PWN-3355 - Real NotificationService integration
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
  app/src/main/java/org/p2p/wallet/push_notifications/api/NotificationServiceApi.kt
  app/src/main/java/org/p2p/wallet/push_notifications/ineractor/PushNotificationsInteractor.kt
  app/src/main/java/org/p2p/wallet/push_notifications/model/DeviceInfo.kt
  app/src/main/java/org/p2p/wallet/push_notifications/model/DeviceToken.kt
  app/src/main/java/org/p2p/wallet/push_notifications/repository/DeviceTokenRemoteRepository.kt
  app/src/main/res/values/environment_config.xml
  solanaj/src/main/java/org/p2p/solanaj/model/types/RpcRequestObject.kt
Labels: Approved by QA

#425 PWN-3250 - Show error when incorrect seed phrase is entered
  app/src/main/java/org/p2p/wallet/common/ui/widget/ProgressButton.kt
  app/src/main/java/org/p2p/wallet/restore/BackupModule.kt
  app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyFragment.kt
  app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyPresenter.kt
  app/src/main/java/org/p2p/wallet/utils/ContextExtensions.kt
  app/src/main/res/drawable/bg_gray_secondary_stroked.xml
  app/src/main/res/layout/dialog_btc_network_info.xml
  app/src/main/res/layout/dialog_btc_topup_info.xml
  app/src/main/res/layout/fragment_auth_done.xml
  app/src/main/res/layout/fragment_create_wallet.xml
  app/src/main/res/layout/fragment_derivable_accounts.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_reserve_username.xml
  app/src/main/res/layout/fragment_reset_seed_phrase.xml
  app/src/main/res/layout/fragment_secret_key.xml
  app/src/main/res/layout/fragment_security_key.xml
  app/src/main/res/layout/widget_progress_button.xml
  app/src/main/res/layout/widget_qr_view.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: Approved by QA

#428 PWN-3084 - Receiving a push messages inside the app
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/p2p/wallet/App.kt
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
  app/src/main/java/org/p2p/wallet/auth/interactor/AuthLogoutInteractor.kt
  app/src/main/java/org/p2p/wallet/auth/ui/done/AuthDonePresenter.kt
  app/src/main/java/org/p2p/wallet/common/di/ServiceScope.kt
  app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
  app/src/main/java/org/p2p/wallet/notification/AppNotificationManager.kt
  app/src/main/java/org/p2p/wallet/notification/FcmPushNotificationData.kt
  app/src/main/java/org/p2p/wallet/push_notifications/AppFirebaseMessagingService.kt
  app/src/main/java/org/p2p/wallet/push_notifications/PushNotificationsModule.kt
  app/src/main/java/org/p2p/wallet/push_notifications/api/NotificationServiceApi.kt
  app/src/main/java/org/p2p/wallet/push_notifications/ineractor/PushNotificationsInteractor.kt
  app/src/main/java/org/p2p/wallet/push_notifications/model/DeviceInfo.kt
  app/src/main/java/org/p2p/wallet/push_notifications/model/DeviceToken.kt
  app/src/main/java/org/p2p/wallet/push_notifications/repository/DeviceTokenRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/push_notifications/repository/DeviceTokenRepository.kt
  app/src/main/java/org/p2p/wallet/push_notifications/repository/PushTokenRepository.kt
  app/src/main/java/org/p2p/wallet/root/RootActivity.kt
  app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsPresenter.kt
  app/src/main/java/org/p2p/wallet/user/UserModule.kt
  app/src/main/res/drawable/ic_app_notification.xml
  app/src/main/res/values/environment_config.xml
Labels: URGENT TO MERGE, WIP

#454 PWN-3462 - Fix Incorrect layout of many application screens
  app/src/main/res/layout/activity_root.xml
  app/src/main/res/layout/fragment_appearance.xml
  app/src/main/res/layout/fragment_buy.xml
  app/src/main/res/layout/fragment_buy_solana.xml
  app/src/main/res/layout/fragment_change_pin.xml
  app/src/main/res/layout/fragment_create_wallet.xml
  app/src/main/res/layout/fragment_derivable_accounts.xml
  app/src/main/res/layout/fragment_moonpay_view.xml
  app/src/main/res/layout/fragment_network_selection.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_receive.xml
  app/src/main/res/layout/fragment_receive_list.xml
  app/src/main/res/layout/fragment_receive_network_type.xml
  app/src/main/res/layout/fragment_receive_ren_btc.xml
  app/src/main/res/layout/fragment_receive_solana.xml
  app/src/main/res/layout/fragment_receive_token.xml
  app/src/main/res/layout/fragment_receiving_statuses.xml
  app/src/main/res/layout/fragment_ren_btc.xml
  app/src/main/res/layout/fragment_ren_transactions.xml
  app/src/main/res/layout/fragment_reset_seed_info.xml
  app/src/main/res/layout/fragment_reset_seed_phrase.xml
  app/src/main/res/layout/fragment_scan_qr.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_secret_key.xml
  app/src/main/res/layout/fragment_security.xml
  app/src/main/res/layout/fragment_security_key.xml
  app/src/main/res/layout/fragment_select_token.xml
  app/src/main/res/layout/fragment_swap_orca.xml
  app/src/main/res/layout/fragment_swap_settings.xml
  app/src/main/res/layout/fragment_token_container.xml
  app/src/main/res/layout/fragment_transaction_transfer.xml
  app/src/main/res/layout/fragment_username.xml
Labels: PR TOO BIG
