Repository p2p-org/key-app-android, pull requests merged in 2023-02, with the labels that each got.

#1213 NO-TICKET - Testing new Swap
  app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
  app/src/main/java/org/p2p/wallet/sdk/RelaySdk.kt
  app/src/main/java/org/p2p/wallet/sdk/facade/AppSdkLogger.kt
  app/src/main/java/org/p2p/wallet/sdk/facade/RelaySdkFacade.kt
  app/src/main/java/org/p2p/wallet/sdk/facade/mapper/SdkMethodResultMapper.kt
  app/src/main/java/org/p2p/wallet/sdk/facade/model/KeyAppSdkMethodResultException.kt
  app/src/main/java/org/p2p/wallet/sdk/facade/model/relay/RelaySdkSignedTransaction.kt
  app/src/main/java/org/p2p/wallet/sdk/facade/model/relay/RelaySignTransactionResponse.kt
  app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/api/SwapJupiterApi.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/api/SwapJupiterTokensApi.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/api/request/CreateSwapTransactionRequest.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/api/request/EmptyRequest.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/api/response/EmptyResponse.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/api/response/tokens/JupiterTokenExtensions.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/api/response/tokens/JupiterTokenResponse.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/domain/JupiterSwapInteractor.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterRemoteMapper.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapRoutesRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapTokenRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapTransactionMapper.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/JupiterSwapTransactionRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/SwapRoutesRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/SwapTokensRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/SwapTransactionRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterSwap.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterSwapFees.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterSwapMarketInformation.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterSwapRoute.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterSwapToken.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterToken.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/SwapFailure.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/SwapMarketInformation.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/SwapRoute.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/routes/JupiterSwapRoutesMapper.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/routes/JupiterSwapRoutesRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/routes/JupiterSwapRoutesRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/tokens/JupiterSwapTokensRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/tokens/JupiterSwapTokensRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/transaction/JupiterSwapTransactionMapper.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/transaction/JupiterSwapTransactionRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/swap/jupiter/repository/transaction/JupiterSwapTransactionRepository.kt
  app/src/main/res/values/environment_config.xml
  app/src/test/java/org/p2p/wallet/sdk/facade/mapper/SolendMethodResultMapperTest.kt
Labels: PR TOO BIG

#1240 PWN-6722 - Separated a version generation, caching properties files and commit changes
  .github/CODEOWNERS
  .github/actions/setup-commit/action.yml
  .github/actions/setup-gradle/action.yml
  .github/actions/setup-version-build/action.yml
  .github/workflows/android-develop-workflow.yml
  .github/workflows/android-feature-workflow.yml
  app/gradle.properties
  bash_scripts/slack_deploy_finish_message.sh
  bash_scripts/slack_deploy_start_message.sh
Labels: Do not review yet, WIP

#1265 PWN-7264 - Provide transaction, to bottom sheet dialog.
  app/gradle.properties
  app/src/main/java/org/p2p/wallet/common/date/ZonedDateExtensions.kt
  app/src/main/java/org/p2p/wallet/history/interactor/HistoryInteractor.kt
  app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt
  app/src/main/java/org/p2p/wallet/history/model/HistoryPagingResult.kt
  app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt
  app/src/main/java/org/p2p/wallet/history/repository/remote/RpcHistoryRepository.kt
  app/src/main/java/org/p2p/wallet/history/ui/details/TransactionDetailsPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListView.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/model/HistoryItem.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/adapter/HistoryAdapter.kt
  app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkEnvironment.kt
  app/src/main/java/org/p2p/wallet/renbtc/model/RenTransaction.kt
  app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidgetModel.kt
  app/src/main/res/layout/fragment_jupiter_swap.xml
  app/src/main/res/layout/layout_token_history_error.xml
  app/src/main/res/layout/widget_swap.xml
  app/src/main/res/menu/menu_jupiter_swap.xml
  app/src/main/res/values/history_strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/swap_strings.xml
  core/src/main/java/org/p2p/core/common/TextContainer.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/drawable/shape/ShapeAppearanceExtensions.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonCellModel.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt
  ui-kit/src/main/res/drawable/ic_receipt_24.xml
  ui-kit/src/main/res/drawable/ic_swap_20.xml
  ui-kit/src/main/res/values/ids.xml
  ui-kit/src/main/res/values/white_palette.xml
Labels: Do not merge, Wrong branch name

#1262 PWN-7263 - History Service Paging
  app/src/main/java/org/p2p/wallet/history/interactor/HistoryInteractor.kt
  app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt
  app/src/main/java/org/p2p/wallet/history/model/HistoryPagingResult.kt
  app/src/main/java/org/p2p/wallet/history/model/HistoryPagingState.kt
  app/src/main/java/org/p2p/wallet/history/repository/remote/HistoryRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/history/repository/remote/HistoryRepository.kt
  app/src/main/java/org/p2p/wallet/history/repository/remote/MoonpayHistoryRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/history/repository/remote/RpcHistoryRepository.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListView.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/model/HistoryItem.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/adapter/HistoryAdapter.kt
  app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
Labels: Wrong branch name

#1288 NO-TICKET - skeleton drawable, small fixes
  core/src/main/java/org/p2p/core/common/TextContainer.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/Shimmer.java
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonCellModel.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonDrawable.java
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonExtensions.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt
Labels: Wrong branch name

#1332 PWN-7425 - Various fixes on Send screen
  app/src/main/java/org/p2p/wallet/common/di/AppScope.kt
  app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FeeCalculationState.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FeePoolsState.kt
  app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerFee.kt
  app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
  app/src/main/java/org/p2p/wallet/newsend/interactor/SendInteractor.kt
  app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonState.kt
  app/src/main/java/org/p2p/wallet/newsend/model/SendSolanaFee.kt
  app/src/main/java/org/p2p/wallet/solend/interactor/SolendDepositInteractor.kt
  app/src/main/java/org/p2p/wallet/solend/interactor/SolendWithdrawInteractor.kt
Labels: URGENT TO MERGE
