Repository p2p-org/key-app-android, pull requests merged in 2023-01, with the labels that each got.

#1085 PWN-6677 - Single line recycler for ActionButton
  app/src/main/java/org/p2p/wallet/common/ui/widget/actionbuttons/ActionButtonsView.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_token_history.xml
  app/src/main/res/layout/layout_action_buttons.xml
Labels: Wrong PR name

#1092 PWN-6740 - Intercom push integratiion
  app/build.gradle
  app/src/main/java/org/p2p/wallet/AppCreatedAction.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
  app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
  app/src/main/java/org/p2p/wallet/intercom/IntercomPushService.kt
  app/src/main/java/org/p2p/wallet/intercom/IntercomService.kt
  app/src/main/java/org/p2p/wallet/push_notifications/AppFirebaseMessagingService.kt
  app/src/main/res/drawable-hdpi/intercom_push_icon.xml
  app/src/main/res/drawable-mdpi/intercom_push_icon.xml
  app/src/main/res/drawable-xhdpi/intercom_push_icon.xml
  app/src/main/res/drawable-xxhdpi/intercom_push_icon.xml
  app/src/main/res/drawable-xxxhdpi/intercom_push_icon.xml
Labels: Approved by QA

#1114 PWN-6722 - Testing release builds
  .github/actions/setup-slack/action.yml
  .github/workflows/android-release-workflow.yml
  scripts/config.gradle
Labels: Do not review yet, WIP

#1147 PWN-6722 - Properties keys cleaning
  .github/actions/setup-apikey/action.yml
  .github/actions/setup-jira-review/action.yml
  .github/actions/setup-project/action.yml
  .github/actions/setup-sentry/action.yml
  .github/actions/setup-torus/action.yml
  .github/workflows/android-develop-workflow.yml
  .github/workflows/android-feature-workflow.yml
  .github/workflows/android-release-workflow.yml
  .gitignore
  app/build.gradle
  app/src/main/java/org/p2p/wallet/App.kt
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/common/analytics/TrackersFactory.kt
  app/src/main/java/org/p2p/wallet/common/crashlogging/impl/FirebaseCrashlyticsFacade.kt
  app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/inapp/DevNetFeatureFlag.kt
  app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/SslPinningFeatureToggle.kt
  app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsPresenter.kt
  bash_scripts/slack_deploy_finish_message.sh
  bash_scripts/slack_deploy_jira_ticket.sh
  bash_scripts/slack_deploy_push_artifacts.sh
  bash_scripts/slack_deploy_start_message.sh
  buildSrc/src/main/groovy/PropertiesFile.groovy
  scripts/analytics.gradle
  scripts/changelog.gradle
  scripts/config.gradle
  scripts/signing.gradle
  scripts/torus.gradle
  scripts/versioning.gradle
Labels: Do not review yet

#1145 PWN-6782 cleanup system bar setting
  app/src/main/java/org/p2p/wallet/auth/ui/animationscreen/AnimationProgressFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/SliderFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/continuestep/ContinueOnboardingFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/pin/validate/ValidatePinFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/ReserveUsernameFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundFragment.kt
  app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenFragment.kt
  app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
  app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenFragment.kt
  app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyFragment.kt
  app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
  app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchFragment.kt
  app/src/main/java/org/p2p/wallet/newsend/ui/stub/SendFeePayerPromptFragment.kt
  app/src/main/java/org/p2p/wallet/newsend/ui/stub/SendUnavailableFragment.kt
  app/src/main/java/org/p2p/wallet/qr/ui/ScanQrFragment.kt
  app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcFragment.kt
  app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenFragment.kt
  app/src/main/java/org/p2p/wallet/root/DecorSystemBarsDelegate.kt
  app/src/main/java/org/p2p/wallet/root/RootActivity.kt
  app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/newreset/main/NewResetPinIntroFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/newreset/pin/NewResetPinFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/recovery/unlock_seed_phrase/SeedPhraseUnlockFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/recovery/user_seed_phrase/UserSeedPhraseFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/reset/seedinfo/SeedInfoFragment.kt
  app/src/main/java/org/p2p/wallet/settings/ui/settings/NewSettingsFragment.kt
  app/src/main/java/org/p2p/wallet/solend/ui/aboutearn/slider/SolendAboutEarnSliderFragment.kt
  app/src/main/java/org/p2p/wallet/splash/SplashFragment.kt
  app/src/main/res/layout/fragment_receive_ren_btc.xml
  app/src/main/res/layout/fragment_seed_phrase_unlock.xml
  app/src/main/res/layout/fragment_user_seed_phrase.xml
Labels: PR TOO BIG

#1180 NO-TICKET - comment old SendPresenterTest.kt
  app/src/test/java/org/p2p/wallet/send/ui/main/SendPresenterTest.kt
Labels: URGENT TO MERGE
