Repository p2p-org/key-app-android, pull requests merged in 2023-03, with the labels that each got.

#1338 PWN-7323 - Fix pull-to-refresh token history
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListView.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewContract.kt
  app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
Labels: URGENT TO MERGE

#1356 PWN-7464 - swap bug fixes
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/info/SwapInfoMapper.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapWidgetMapper.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/JupiterSwapSettingsFragment.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/adapter/SwapSettingsDecorator.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/presenter/SwapContentSettingsMapper.kt
  app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/view/SwapCustomSlippageCell.kt
  app/src/main/res/layout/item_swap_custom_slippage.xml
  app/src/main/res/values/swap_strings.xml
  core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt
  ui-kit/src/main/res/values/ids.xml
Labels: Wrong branch name

#1352 PWN-7343 - get prices on Ethereum tokens and tests on it
  app/src/main/java/org/p2p/wallet/AppModule.kt
  app/src/main/java/org/p2p/wallet/home/api/CoinGeckoApi.kt
  app/src/main/java/org/p2p/wallet/home/api/CoinGeckoEthereumPrice.kt
  app/src/main/java/org/p2p/wallet/home/model/TokenConverter.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/TokenAddress.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/di/TokenPricesModule.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCryptoCompareRepository.kt
  core/src/main/java/org/p2p/core/token/Token.kt
  ethereumkit/schemas/org.p2p.ethereumkit.internal.spv.core.storage.SpvDatabase/2.json
  ethereumkit/schemas/org.p2p.ethereumkit.spv.core.storage.SpvDatabase/2.json
  ethereumkit/src/main/java/org/p2p/ethereumkit/EthereumKitService.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/EthereumModule.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/EthereumNetworkModule.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/AlchemyService.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/request/GetBalanceJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/request/GetTokenBalancesJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/request/GetTokenMetadataJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/response/TokenBalancesResponse.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/coingecko/CoinGeckoService.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/coingecko/response/CoinGeckoPriceResponse.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/balance/BalanceRepository.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/balance/EthereumTokensRemoteRepository.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/balance/TokensRepository.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/core/CoroutineDispatchers.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthTokenKeyProvider.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthTokenMetadata.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/price/EthereumPriceRepository.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/price/PriceRepository.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumRepository.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/utils/EthereumUtils.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/core/RpcBlockchain.kt
  ethereumkit/src/test/java/org/p2p/ethereumkit/EthereumBalanceTest.kt
  ethereumkit/src/test/java/org/p2p/ethereumkit/EthereumKeyPairGeneratorTest.kt
  ethereumkit/src/test/java/org/p2p/ethereumkit/TestCoroutineDispatcher.kt
  ethereumkit/src/test/java/org/p2p/ethereumkit/TokenBalancesTest.kt
Labels: PR TOO BIG

#1371 PWN-7343 - Fix bug with BKS provider
  app/proguard-rules.pro
Labels: Wrong branch name

#1412 PWN-7381 - Fix receive sol MR comments
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
  app/src/main/java/org/p2p/wallet/newsend/ui/stub/SendUnavailableFragment.kt
  app/src/main/java/org/p2p/wallet/qr/ScanQrModule.kt
  app/src/main/java/org/p2p/wallet/receive/solana/NewReceiveSolanaFragment.kt
  app/src/main/res/layout/fragment_new_receive_solana.xml
Labels: Wrong branch name

#1411 PWN-7595 - First step of Bridge API integration
  app/src/main/java/org/p2p/wallet/claim/api/BridgeApi.kt
  app/src/main/java/org/p2p/wallet/claim/api/mapper/BridgeServiceErrorMapper.kt
  app/src/main/java/org/p2p/wallet/claim/api/request/GetClaimFeeRpcRequest.kt
  app/src/main/java/org/p2p/wallet/claim/api/request/SendBundleRpcRequest.kt
  app/src/main/java/org/p2p/wallet/claim/api/request/TransferErc20TokenRpcRequest.kt
  app/src/main/java/org/p2p/wallet/claim/api/request/TransferEthRpcRequest.kt
  app/src/main/java/org/p2p/wallet/claim/api/response/BridgeBundleResponse.kt
  app/src/main/java/org/p2p/wallet/claim/api/response/BridgeErrorResponse.kt
  app/src/main/java/org/p2p/wallet/claim/api/response/BundleAmountResponse.kt
  app/src/main/java/org/p2p/wallet/claim/api/response/BundleFeeResponse.kt
  app/src/main/java/org/p2p/wallet/claim/model/BridgeBundle.kt
  app/src/main/java/org/p2p/wallet/claim/model/BridgeServiceError.kt
  app/src/main/java/org/p2p/wallet/claim/model/BundleFee.kt
  app/src/main/java/org/p2p/wallet/utils/HexString.kt
  core/src/main/java/org/p2p/core/token/SolAddress.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/EthereumNetworkModule.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/request/GetBalanceJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/request/GetTokenBalancesJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/request/GetTokenMetadataJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/external/core/GsonProvider.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/core/ApiRpcSyncer.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/core/Interfaces.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/core/NodeApiProvider.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/core/NodeWebSocket.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/core/RpcBlockchain.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/core/WebSocketRpcSyncer.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/DataJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/GetBlockByNumberJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/GetLogsJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/GetTransactionByHashJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/GetTransactionReceiptJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/JsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/LongJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/api/jsonrpc/SubscribeJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/core/EthereumKit.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/core/Interfaces.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/core/eip1559/FeeHistoryJsonRpc.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/network/GsonTypeAdapters.kt
  ethereumkit/src/main/java/org/p2p/ethereumkit/internal/spv/core/SpvBlockchain.kt
Labels: PR TOO BIG

#1424 WIP: PWN-7662 - New Swap. Remove inifinite loading on startRefreshJob
  app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt
Labels: Do not merge

#1444 PWN-7708 small amount error
  app/src/main/java/org/p2p/wallet/jupiter/repository/model/SwapFailure.kt
  app/src/main/java/org/p2p/wallet/jupiter/repository/routes/JupiterSwapRoutesRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapFeatureException.kt
  app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt
  app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateRoutesRefresher.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt
Labels: URGENT TO MERGE

#1454 PWN-7752 PWN-7759 - New Swap. Replace BTC ETH to UX friendly names
  app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/ContentTypeInterceptor.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/tokens/presenter/SwapTokensBMapper.kt
  app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCoinGeckoRepository.kt
  buildSrc/src/main/java/AppVersions.kt
  core/src/main/java/org/p2p/core/utils/Constants.kt
Labels: HOTFIX

#1486 WIP: Release/v2.5.0.8
  .github/workflows/release-build.yml
  app/src/main/java/org/p2p/wallet/jupiter/statemanager/rate/SwapRateTickerManager.kt
Labels: Do not merge

#1523 PWN-7927 - Fix SOL rate in DerivableAccountFragment
  app/src/main/java/org/p2p/wallet/restore/RestoreModule.kt
  app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
  app/src/main/java/org/p2p/wallet/restore/model/DerivableAccount.kt
  app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsAdapter.kt
  app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsPresenter.kt
  buildSrc/src/main/java/AppVersions.kt
Labels: URGENT TO MERGE, HOTFIX
