Repository p2p-org/key-app-android, pull requests merged in 2023-07, with the labels that each got.

#1904 PWN-9119 - Create Database for saving token prices
  app/build.gradle.kts
  app/src/main/java/org/p2p/wallet/home/model/TokenConverter.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeInteractor.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
  app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/UserSendLinksDatabaseRepository.kt
  app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/jupiter/statemanager/rate/SwapRateTickerManager.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/main/SwapTokenRateLoader.kt
  app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt
  app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsPresenter.kt
  app/src/main/java/org/p2p/wallet/solend/model/SolendDepositMapper.kt
  app/src/main/java/org/p2p/wallet/solend/repository/SolendDepositsRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/striga/wallet/interactor/StrigaClaimInteractor.kt
  app/src/main/java/org/p2p/wallet/svl/interactor/ReceiveViaLinkInteractor.kt
  app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserLocalRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/user/repository/UserTokensDatabaseRepository.kt
  app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterTestPresenterBuilder.kt
  core/build.gradle.kts
  core/src/main/java/org/p2p/core/room/RoomConverters.kt
  token-service/build.gradle.kts
  token-service/src/main/java/org/p2p/token/service/TokenServiceModule.kt
  token-service/src/main/java/org/p2p/token/service/api/events/manager/TokenServiceEvent.kt
  token-service/src/main/java/org/p2p/token/service/api/events/manager/TokenServiceEventPublisher.kt
  token-service/src/main/java/org/p2p/token/service/api/mapper/TokenServiceMapper.kt
  token-service/src/main/java/org/p2p/token/service/api/response/TokenItemMetadataResponse.kt
  token-service/src/main/java/org/p2p/token/service/api/response/TokenItemPriceResponse.kt
  token-service/src/main/java/org/p2p/token/service/api/response/TokenRateResponse.kt
  token-service/src/main/java/org/p2p/token/service/database/TokenPriceDao.kt
  token-service/src/main/java/org/p2p/token/service/database/TokenServiceDatabase.kt
  token-service/src/main/java/org/p2p/token/service/database/TokenServiceDatabaseModule.kt
  token-service/src/main/java/org/p2p/token/service/database/entity/TokenPriceEntity.kt
  token-service/src/main/java/org/p2p/token/service/database/mapper/TokenServiceDatabaseMapper.kt
  token-service/src/main/java/org/p2p/token/service/model/TokenRate.kt
  token-service/src/main/java/org/p2p/token/service/model/TokenServiceMetadata.kt
  token-service/src/main/java/org/p2p/token/service/model/TokenServiceNetwork.kt
  token-service/src/main/java/org/p2p/token/service/model/TokenServicePrice.kt
  token-service/src/main/java/org/p2p/token/service/repository/TokenServiceRepository.kt
  token-service/src/main/java/org/p2p/token/service/repository/TokenServiceRepositoryImpl.kt
  token-service/src/main/java/org/p2p/token/service/repository/price/TokenPriceDatabaseRepository.kt
  token-service/src/main/java/org/p2p/token/service/repository/price/TokenPriceInMemoryRepository.kt
  token-service/src/main/java/org/p2p/token/service/repository/price/TokenPriceLocalRepository.kt
  token-service/src/main/java/org/p2p/token/service/repository/price/TokenPriceRemoteRepository.kt
Labels: PR TOO BIG

#1905 NO-TICKET - refactor and migrate MainContainerFragment.kt on ViewPager2
  app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
  app/src/main/java/org/p2p/wallet/common/ui/BaseFragmentAdapter.kt
  app/src/main/java/org/p2p/wallet/common/ui/FragmentPageConfiguration.kt
  app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerContract.kt
  app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerFragment.kt
  app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt
  app/src/main/java/org/p2p/wallet/home/ui/container/ScreenConfiguration.kt
  app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapFragment.kt
  app/src/main/java/org/p2p/wallet/solend/ui/aboutearn/SolendAboutEarnFragment.kt
  app/src/main/java/org/p2p/wallet/solend/ui/info/SolendInfoBottomSheet.kt
  app/src/main/res/layout/fragment_main.xml
Labels: Do not merge

#1928 NO-TICKET - kover coverage improvements
  .github/workflows/pull-request-check.yml
  app/build.gradle.kts
  core/src/main/java/org/p2p/core/utils/NoCoverage.kt
Labels: Do not merge

#1992 PWN-9269 - striga. off ramp exchange calculator
  app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletContract.kt
  app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletFragment.kt
  app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/main/mapper/SwapRateTickerMapper.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/main/widget/SwapWidget.kt
  app/src/main/java/org/p2p/wallet/striga/StrigaModule.kt
  app/src/main/java/org/p2p/wallet/striga/exchange/StrigaExchangeModule.kt
  app/src/main/java/org/p2p/wallet/striga/exchange/models/StrigaExchangePairsWithRates.kt
  app/src/main/java/org/p2p/wallet/striga/exchange/models/StrigaExchangeRate.kt
  app/src/main/java/org/p2p/wallet/striga/exchange/repository/StrigaExchangeRepository.kt
  app/src/main/java/org/p2p/wallet/striga/exchange/repository/impl/StrigaExchangeRemoteRepository.kt
  app/src/main/java/org/p2p/wallet/striga/exchange/repository/mapper/StrigaExchangeRepositoryMapper.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/StrigaOffRampContract.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/StrigaOffRampModule.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/interactor/StrigaOffRampInteractor.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/interactor/polling/StrigaOffRampExchangeRateNotifier.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/mappers/StrigaOffRampMapper.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/mappers/StrigaOffRampSwapWidgetMapper.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/models/StrigaOffRampButtonState.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/models/StrigaOffRampRateState.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/models/StrigaOffRampTokenState.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/models/StrigaOffRampTokenType.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampFragment.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenter.kt
  app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampViewState.kt
  app/src/main/res/layout/fragment_striga_off_ramp.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/striga_strings.xml
  app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterBaseTest.kt
  app/src/test/java/org/p2p/wallet/striga/exchange/repository/StrigaExchangeRepositoryTest.kt
  app/src/test/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenterBaseTest.kt
  app/src/test/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenterCalculationTest.kt
  app/src/test/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenterInitialStateTest.kt
  app/src/test/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenterNextButtonTest.kt
  app/src/test/java/org/p2p/wallet/striga/signup/validation/PhoneNumberInputValidatorTest.kt
  app/src/test/java/org/p2p/wallet/utils/AppTestUtils.kt
  test-utils/src/main/java/org/p2p/wallet/utils/StandardTestCoroutineDispatchers.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/natives/UiKitSnackbar.kt
  ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt
Labels: PR TOO BIG

#2005 PWN-9275 - refactor bottomsheet to handle needed progress with ProgressHandlers
  app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimFragment.kt
  app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt
  app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendFragment.kt
  app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt
  app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt
  app/src/main/java/org/p2p/wallet/home/events/PendingClaimBundlesLoader.kt
  app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoFragment.kt
  app/src/main/java/org/p2p/wallet/home/ui/crypto/handlers/BridgeClaimBundleClickHandler.kt
  app/src/main/java/org/p2p/wallet/infrastructure/transactionmanager/TransactionManager.kt
  app/src/main/java/org/p2p/wallet/infrastructure/transactionmanager/impl/TransactionManagerImpl.kt
  app/src/main/java/org/p2p/wallet/infrastructure/transactionmanager/repository/TransactionQueueRepository.kt
  app/src/main/java/org/p2p/wallet/infrastructure/transactionmanager/repository/TransactionQueueRepositoryImpl.kt
  app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt
  app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
  app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
  app/src/main/java/org/p2p/wallet/root/RootActivity.kt
  app/src/main/java/org/p2p/wallet/root/RootListener.kt
  app/src/main/java/org/p2p/wallet/transaction/di/TransactionModule.kt
  app/src/main/java/org/p2p/wallet/transaction/model/TransactionState.kt
  app/src/main/java/org/p2p/wallet/transaction/model/progressstate/BridgeSendProgressState.kt
  app/src/main/java/org/p2p/wallet/transaction/model/progressstate/ClaimProgressState.kt
  app/src/main/java/org/p2p/wallet/transaction/model/progressstate/JupiterSwapProgressState.kt
  app/src/main/java/org/p2p/wallet/transaction/model/progressstate/SendSwapProgressState.kt
  app/src/main/java/org/p2p/wallet/transaction/model/progressstate/TransactionState.kt
  app/src/main/java/org/p2p/wallet/transaction/progresshandler/BridgeSendProgressHandler.kt
  app/src/main/java/org/p2p/wallet/transaction/progresshandler/ClaimProgressHandler.kt
  app/src/main/java/org/p2p/wallet/transaction/progresshandler/SendSwapTransactionProgressHandler.kt
  app/src/main/java/org/p2p/wallet/transaction/progresshandler/TransactionProgressHandler.kt
  app/src/main/java/org/p2p/wallet/transaction/ui/JupiterTransactionProgressBottomSheet.kt
  app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt
  app/src/main/java/org/p2p/wallet/transaction/ui/ProgressBottomSheet.kt
Labels: PR TOO BIG

#2045 NO-TICKET - Fix field name for token-service
  token-service/src/main/java/org/p2p/token/service/api/response/TokenListResponse.kt
Labels: URGENT TO MERGE
